services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: moja-strona-dev
    ports:
      # Port dla Vite (frontend)
      - "5173:5173"
    environment:
      - VERCEL_TOKEN=${VERCEL_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Synchronizacja kodu lokalnego z kontenerem
      - .:/app
      # Zapobiega nadpisywaniu node_modules w kontenerze przez lokalny (je≈õli istnieje)
      - nodemodules:/app/node_modules

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moja-strona-prod
    environment:
      - VERCEL_TOKEN=${VERCEL_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - proxy-network

volumes:
  nodemodules:

networks:
  proxy-network:
    external: true


