services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: moja-strona-dev
    ports:
      - "5173:5173"
    environment:
      - VERCEL_TOKEN=${VERCEL_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - nodemodules:/app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - services-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - TARGET_EMAIL=${TARGET_EMAIL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    networks:
      - services-network

volumes:
  nodemodules:

networks:
  services-network:
    external: true


